import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/styles/globals.css'
import ReactQueryClientProviders from '@/libs/react-query-client-provider'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'Climate weather app',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} antialiased w-full min-h-screen bg-primary-500 bg-hero-pattern bg-cover bg-center bg-no-repeat`}
            >
                <div className="relative w-full min-h-screen p-4 backdrop-blur-lg flex items-center justify-center flex-col">
                    <ReactQueryClientProviders>
                        {children}
                    </ReactQueryClientProviders>
                </div>
            </body>
        </html>
    )
}
